{pkgs, ...}: {
  home.packages = [
    (import ./reload.nix {inherit pkgs;})
    (import ./cycleWorkspace.nix {inherit pkgs;})
    (import ./completeOrphan.nix {inherit pkgs;})
    (import ./createWorkspace.nix {inherit pkgs;})
    (import ./moveWorkspace.nix {inherit pkgs;})
    (import ./moveWindow.nix {inherit pkgs;})
    (import ./deflate.nix {inherit pkgs;})
    (import ./compareDir.nix {inherit pkgs;})
    (import ./hyprpaperManager.nix {inherit pkgs;})
    (import ./toggleLightMode.nix {inherit pkgs;})
    (import ./createMacro.nix {inherit pkgs;})
    # <MACRO INSERT>
    (import ./ssht.nix {inherit pkgs;})
    (import ./nix-full-clean.nix {inherit pkgs;})
    (import ./screenRecord.nix {inherit pkgs;})
    (import ./7zip.nix {inherit pkgs;})
    (import ./denode.nix {inherit pkgs;})
    (import ./rs.nix {inherit pkgs;})
    (import ./rn-regex.nix {inherit pkgs;})
    (import ./mv-regex.nix {inherit pkgs;})
    (import ./cp-regex.nix {inherit pkgs;})
    (import ./git-clone-regex.nix {inherit pkgs;})
    (import ./rm-regex.nix {inherit pkgs;})
    (import ./nix-find.nix {inherit pkgs;})
    (import ./watchWindow.nix {inherit pkgs;})
    (import ./listMacros.nix {inherit pkgs;})
    (import ./hssh.nix {inherit pkgs;})
    (import ./nix-repl.nix {inherit pkgs;})
    (import ./newAlias.nix {inherit pkgs;})
    (import ./newMacro.nix {inherit pkgs;})
    (import ./createAlias.nix {inherit pkgs;})
    (import ./git_plog.nix {inherit pkgs;})
    (import ./hardReboot.nix {inherit pkgs;})
    (import ./lineCounter.nix {inherit pkgs;})
    (import ./watchBuffer.nix {inherit pkgs;})
    (import ./shell.nix {inherit pkgs;})
    (import ./copyJsConfig.nix {inherit pkgs;})
  ];
}
